(* syscfg.CLKDIV = 3'd0 *)
module comb_and8 (CLK, CLBSWIN0,CLBSWIN1,CLBSWIN2,CLBSWIN3,CLBSWIN4,CLBSWIN5,CLBSWIN6,CLBSWIN7, o0, o1);
    input CLK, CLBSWIN0,CLBSWIN1,CLBSWIN2,CLBSWIN3,CLBSWIN4,CLBSWIN5,CLBSWIN6,CLBSWIN7;
    output o0, o1;
    reg r0=0, r1=0;
    always @(posedge CLK) begin
        r0 <= CLBSWIN0&CLBSWIN1&CLBSWIN2&CLBSWIN3&CLBSWIN4&CLBSWIN5&CLBSWIN6&CLBSWIN7;
        r1 <= CLBSWIN0|CLBSWIN1|CLBSWIN2|CLBSWIN3|CLBSWIN4|CLBSWIN5|CLBSWIN6|CLBSWIN7;
    end
    assign o0=r0; assign o1=r1;
endmodule
